# -*- coding: utf-8 -*-
##############################################################################
#
#    Author: Benoit Guillot
#    Copyright 2014 Akretion
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

"""
Magento responses for calls done by the connector.

This set of responses has been recorded for the synchronizations
with a Magento 1.7 version with demo data.

It has been recorded using ``magentoerpconnect.unit.backend_adapter.record``
and ``magentoerpconnect.unit.backend_adapter.output_recorder``
"""
import time


FMT = "%Y-%m-%d %H:%M:%S"


magento_comment_responses = \
{('catalog_category.info', (1, None, None)): {'all_children': '1,3,10,22,23,13,12,25,26,15,27,28,29,30,31,32,33,34,8,18,19,4,5,16,17',
                                              'available_sort_by': None,
                                              'category_id': '1',
                                              'children': '3',
                                              'created_at': '2007-07-20 18:46:08',
                                              'custom_apply_to_products': None,
                                              'custom_design': None,
                                              'custom_design_from': None,
                                              'custom_design_to': None,
                                              'custom_layout_update': None,
                                              'custom_use_parent_settings': None,
                                              'default_sort_by': None,
                                              'description': None,
                                              'display_mode': None,
                                              'filter_price_range': None,
                                              'image': None,
                                              'include_in_menu': '1',
                                              'increment_id': None,
                                              'is_active': '1',
                                              'is_anchor': None,
                                              'landing_page': None,
                                              'level': '0',
                                              'meta_description': None,
                                              'meta_keywords': None,
                                              'meta_title': None,
                                              'name': None,
                                              'page_layout': None,
                                              'parent_id': 0,
                                              'path': '1',
                                              'path_in_store': None,
                                              'position': '1',
                                              'thumbnail': None,
                                              'updated_at': '2007-08-07 09:50:15',
                                              'url_key': None,
                                              'url_path': None},
 ('catalog_category.info', (3, None, None)): {'all_children': '3,10,22,23,13,12,25,26,15,27,28,29,30,31,32,33,34,8,18,19,4,5,16,17',
                                              'available_sort_by': None,
                                              'category_id': '3',
                                              'children': '10,13,18',
                                              'created_at': '2007-08-22 15:54:41',
                                              'custom_apply_to_products': None,
                                              'custom_design': None,
                                              'custom_design_from': None,
                                              'custom_design_to': None,
                                              'custom_layout_update': None,
                                              'custom_use_parent_settings': None,
                                              'default_sort_by': None,
                                              'description': None,
                                              'display_mode': 'PRODUCTS',
                                              'filter_price_range': None,
                                              'image': None,
                                              'include_in_menu': '1',
                                              'increment_id': None,
                                              'is_active': '1',
                                              'is_anchor': None,
                                              'landing_page': None,
                                              'level': '1',
                                              'meta_description': None,
                                              'meta_keywords': None,
                                              'meta_title': None,
                                              'name': 'Root Catalog',
                                              'page_layout': None,
                                              'parent_id': 1,
                                              'path': '1/3',
                                              'path_in_store': '',
                                              'position': '3',
                                              'thumbnail': None,
                                              'updated_at': '2007-12-05 04:38:59',
                                              'url_key': 'root-catalog',
                                              'url_path': None},
 ('catalog_category.info', (8, None, None)): {'all_children': '8',
                                              'available_sort_by': None,
                                              'category_id': '8',
                                              'children': '',
                                              'created_at': '2007-08-22 18:10:30',
                                              'custom_apply_to_products': '1',
                                              'custom_design': '',
                                              'custom_design_from': None,
                                              'custom_design_to': None,
                                              'custom_layout_update': '',
                                              'custom_use_parent_settings': '1',
                                              'default_sort_by': None,
                                              'description': '',
                                              'display_mode': 'PRODUCTS_AND_PAGE',
                                              'filter_price_range': None,
                                              'image': None,
                                              'include_in_menu': '1',
                                              'increment_id': None,
                                              'is_active': '1',
                                              'is_anchor': '1',
                                              'landing_page': '4',
                                              'level': '3',
                                              'meta_description': '',
                                              'meta_keywords': '',
                                              'meta_title': '',
                                              'name': 'Cell Phones',
                                              'page_layout': '',
                                              'parent_id': 13,
                                              'path': '1/3/13/8',
                                              'path_in_store': '8,13',
                                              'position': '8',
                                              'thumbnail': None,
                                              'updated_at': '2008-08-07 23:51:26',
                                              'url_key': 'cell-phones',
                                              'url_path': 'electronics/cell-phones.html'},
 ('catalog_category.info', (13, None, None)): {'all_children': '13,12,25,26,15,27,28,29,30,31,32,33,34,8',
                                               'available_sort_by': None,
                                               'category_id': '13',
                                               'children': '8,12,15',
                                               'created_at': '2007-08-24 13:31:01',
                                               'custom_apply_to_products': None,
                                               'custom_design': None,
                                               'custom_design_from': None,
                                               'custom_design_to': None,
                                               'custom_layout_update': None,
                                               'custom_use_parent_settings': None,
                                               'default_sort_by': None,
                                               'description': None,
                                               'display_mode': 'PAGE',
                                               'filter_price_range': None,
                                               'image': None,
                                               'include_in_menu': '1',
                                               'increment_id': None,
                                               'is_active': '1',
                                               'is_anchor': '1',
                                               'landing_page': '3',
                                               'level': '2',
                                               'meta_description': None,
                                               'meta_keywords': None,
                                               'meta_title': None,
                                               'name': 'Electronics',
                                               'page_layout': 'one_column',
                                               'parent_id': 3,
                                               'path': '1/3/13',
                                               'path_in_store': '13',
                                               'position': '13',
                                               'thumbnail': None,
                                               'updated_at': '2008-08-08 00:02:23',
                                               'url_key': 'electronics',
                                               'url_path': 'electronics.html'},
 ('catalog_product.info', (166, None, None, 'id')): {'activation_information': '',
                                                     'categories': ['8'],
                                                     'color': '24',
                                                     'cost': None,
                                                     'country_of_manufacture': None,
                                                     'created_at': '2008-07-25 02:22:13',
                                                     'custom_design': '',
                                                     'custom_design_from': None,
                                                     'custom_design_to': None,
                                                     'custom_layout_update': '',
                                                     'description': u'Re-defining the perception of advanced mobile phones\u2026 the HTC Touch Diamond\u2122 signals a giant leap forward in combining hi-tech prowess with intuitive usability and exhilarating design.\r\n\r\nFeaturing a sharp 2.8-inch touch screen housed within a stunning formation of brushed metal and flawless faceted edges, the HTC Touch Diamond is as beautiful to behold as it is to use.\r\n\r\nWith HTC\u2019s vibrant touch-responsive user interface, TouchFLO\u2122 3D, and ultra-fast HSDPA internet connectivity\u2026 the HTC Touch Diamond offers a rich online experience to rival a notebook computer, allowing you to interact with Google, YouTube, and Wikipedia as freely as you would with a broadband connection.\r\n\r\nYour contacts, favourite music, videos and photos are no longer an uninspired line of text. With TouchFLO 3D, album artwork, video stills and snapshots of your friends\u2019 and family\u2019s faces are brought to life for you to interact, play and launch at your fingertips.\r\n\r\nA 3.2 megapixel auto-focus camera will help you capture the perfect moment in style and with a massive 4GB of internal storage you can keep all the files you need. The integrated ultra-sensitive GPS will help you find your destination as quickly and efficiently as a dedicated satellite navigation unit.\r\n\r\nStyle and substance in a phone are no longer mutually exclusive. The HTC Touch Diamond has arrived.',
                                                     'dimension': '102 mm (L) X 51 mm (W) X 11.35 mm (T)',
                                                     'enable_googlecheckout': None,
                                                     'gift_message_available': '',
                                                     'group_price': [],
                                                     'has_options': '0',
                                                     'image_label': None,
                                                     'in_depth': u'Re-defining the perception of advanced mobile phones\u2026 the HTC Touch Diamond\u2122 signals a giant leap forward in combining hi-tech prowess with intuitive usability and exhilarating design.\r\n\r\nFeaturing a sharp 2.8-inch touch screen housed within a stunning formation of brushed metal and flawless faceted edges, the HTC Touch Diamond is as beautiful to behold as it is to use.\r\n\r\nWith HTC\u2019s vibrant touch-responsive user interface, TouchFLO\u2122 3D, and ultra-fast HSDPA internet connectivity\u2026 the HTC Touch Diamond offers a rich online experience to rival a notebook computer, allowing you to interact with Google, YouTube, and Wikipedia as freely as you would with a broadband connection.\r\n\r\nYour contacts, favourite music, videos and photos are no longer an uninspired line of text. With TouchFLO 3D, album artwork, video stills and snapshots of your friends\u2019 and family\u2019s faces are brought to life for you to interact, play and launch at your fingertips.\r\n\r\nA 3.2 megapixel auto-focus camera will help you capture the perfect moment in style and with a massive 4GB of internal storage you can keep all the files you need. The integrated ultra-sensitive GPS will help you find your destination as quickly and efficiently as a dedicated satellite navigation unit.\r\n\r\nStyle and substance in a phone are no longer mutually exclusive. The HTC Touch Diamond has arrived.',
                                                     'is_recurring': None,
                                                     'manufacturer': '122',
                                                     'meta_description': '',
                                                     'meta_keyword': '',
                                                     'meta_title': '',
                                                     'minimal_price': None,
                                                     'model': 'HTC Touch Diamond',
                                                     'msrp': None,
                                                     'msrp_display_actual_price_type': None,
                                                     'msrp_enabled': None,
                                                     'name': 'HTC Touch Diamond',
                                                     'news_from_date': None,
                                                     'news_to_date': None,
                                                     'old_id': None,
                                                     'options_container': 'container2',
                                                     'page_layout': None,
                                                     'price': '750.0000',
                                                     'product_id': '166',
                                                     'recurring_profile': None,
                                                     'required_options': '0',
                                                     'set': '38',
                                                     'short_description': u'Re-defining the perception of advanced mobile phones\u2026 the HTC Touch Diamond\u2122 signals a giant leap forward in combining hi-tech prowess with intuitive usability and exhilarating design.',
                                                     'sku': 'HTC Touch Diamond',
                                                     'small_image_label': None,
                                                     'special_from_date': None,
                                                     'special_price': None,
                                                     'special_to_date': None,
                                                     'status': '1',
                                                     'tax_class_id': '2',
                                                     'thumbnail_label': None,
                                                     'tier_price': [],
                                                     'type': 'simple',
                                                     'type_id': 'simple',
                                                     'updated_at': '2008-07-25 02:22:44',
                                                     'url_key': 'htc-touch-diamond',
                                                     'url_path': 'htc-touch-diamond.html',
                                                     'visibility': '4',
                                                     'websites': ['1'],
                                                     'weight': '0.3000'},
 ('customer.info', (1, None)): {'confirmation': None,
                                'created_at': '2007-08-30 23:23:13',
                                'created_in': None,
                                'customer_id': '1',
                                'default_billing': '274',
                                'default_shipping': '274',
                                'disable_auto_group_change': '0',
                                'dob': None,
                                'email': 'john.doe@example.com',
                                'firstname': 'John',
                                'gender': None,
                                'group_id': '1',
                                'increment_id': '000000001',
                                'lastname': 'Doe',
                                'middlename': '',
                                'password_hash': '585d7096dfbd65ca3a9e07f5e7644fbe:fq',
                                'prefix': '',
                                'rp_token': None,
                                'rp_token_created_at': None,
                                'store_id': '1',
                                'suffix': '',
                                'taxvat': '',
                                'updated_at': '2014-03-14 16:10:46',
                                'website_id': '1'},
 ('customer_address.info', (5, None)): {'city': 'Vi',
                                        'company': None,
                                        'country_id': 'FR',
                                        'created_at': '2014-01-08 14:38:02',
                                        'customer_address_id': '5',
                                        'fax': None,
                                        'firstname': 'john',
                                        'increment_id': None,
                                        'is_default_billing': False,
                                        'is_default_shipping': False,
                                        'lastname': 'doe',
                                        'middlename': None,
                                        'postcode': '69100',
                                        'prefix': None,
                                        'region': u'Ari\xe8ge',
                                        'region_id': '190',
                                        'street': '5',
                                        'suffix': None,
                                        'telephone': '25',
                                        'updated_at': '2014-03-14 16:10:46',
                                        'vat_id': None,
                                        'vat_is_valid': None,
                                        'vat_request_date': None,
                                        'vat_request_id': None,
                                        'vat_request_success': None},
 ('customer_address.list', (frozenset([('customer_id', frozenset([('eq', '1')]))]),)): [{'city': 'Vi',
                                                                                         'country_id': 'FR',
                                                                                         'created_at': '2014-01-08 14:38:02',
                                                                                         'customer_address_id': '5',
                                                                                         'firstname': 'john',
                                                                                         'is_default_billing': False,
                                                                                         'is_default_shipping': False,
                                                                                         'lastname': 'doe',
                                                                                         'postcode': '69100',
                                                                                         'region': u'Ari\xe8ge',
                                                                                         'region_id': '190',
                                                                                         'street': '5',
                                                                                         'telephone': '25',
                                                                                         'updated_at': '2014-03-14 16:10:46'}],
 ('ol_customer_groups.info', (1, None)): {'customer_group_code': 'General',
                                          'customer_group_id': '1',
                                          'tax_class_id': '3'},
 ('product_media.list', (166, None, 'id')): [{'exclude': '1',
                                              'file': '/h/t/htc-touch-diamond.jpg',
                                              'label': '',
                                              'position': '1',
                                              'types': ['thumbnail',
                                                        'small_image',
                                                        'image'],
                                              'url': 'http://localhost:9100/media/catalog/product/h/t/htc-touch-diamond.jpg'}],
 ('sales_order.info', ('100000006', None)): {'adjustment_negative': None,
                                             'adjustment_positive': None,
                                             'applied_rule_ids': None,
                                             'base_adjustment_negative': None,
                                             'base_adjustment_positive': None,
                                             'base_currency_code': 'EUR',
                                             'base_custbalance_amount': None,
                                             'base_discount_amount': '0.0000',
                                             'base_discount_canceled': None,
                                             'base_discount_invoiced': None,
                                             'base_discount_refunded': None,
                                             'base_grand_total': '755.0000',
                                             'base_hidden_tax_amount': '0.0000',
                                             'base_hidden_tax_invoiced': None,
                                             'base_hidden_tax_refunded': None,
                                             'base_shipping_amount': '5.0000',
                                             'base_shipping_canceled': None,
                                             'base_shipping_discount_amount': '0.0000',
                                             'base_shipping_hidden_tax_amnt': '0.0000',
                                             'base_shipping_hidden_tax_amount': '0.0000',
                                             'base_shipping_incl_tax': '5.0000',
                                             'base_shipping_invoiced': None,
                                             'base_shipping_refunded': None,
                                             'base_shipping_tax_amount': '0.0000',
                                             'base_shipping_tax_refunded': None,
                                             'base_subtotal': '750.0000',
                                             'base_subtotal_canceled': None,
                                             'base_subtotal_incl_tax': '750.0000',
                                             'base_subtotal_invoiced': None,
                                             'base_subtotal_refunded': None,
                                             'base_tax_amount': '0.0000',
                                             'base_tax_canceled': None,
                                             'base_tax_invoiced': None,
                                             'base_tax_refunded': None,
                                             'base_to_global_rate': '1.0000',
                                             'base_to_order_rate': '1.0000',
                                             'base_total_canceled': None,
                                             'base_total_due': None,
                                             'base_total_invoiced': None,
                                             'base_total_invoiced_cost': None,
                                             'base_total_offline_refunded': None,
                                             'base_total_online_refunded': None,
                                             'base_total_paid': None,
                                             'base_total_qty_ordered': None,
                                             'base_total_refunded': None,
                                             'billing_address': {'address_id': '211',
                                                                 'address_type': 'billing',
                                                                 'city': 'Vi',
                                                                 'company': None,
                                                                 'country_id': 'FR',
                                                                 'customer_address_id': '5',
                                                                 'customer_id': '1',
                                                                 'email': None,
                                                                 'fax': None,
                                                                 'firstname': 'john',
                                                                 'gift_message_id': None,
                                                                 'lastname': 'doe',
                                                                 'middlename': None,
                                                                 'parent_id': '106',
                                                                 'postcode': '69100',
                                                                 'prefix': None,
                                                                 'quote_address_id': None,
                                                                 'region': u'Ari\xe8ge',
                                                                 'region_id': '190',
                                                                 'street': '5',
                                                                 'suffix': None,
                                                                 'tax_id': None,
                                                                 'telephone': '25',
                                                                 'vat_id': None,
                                                                 'vat_is_valid': None,
                                                                 'vat_request_date': None,
                                                                 'vat_request_id': None,
                                                                 'vat_request_success': None},
                                             'billing_address_id': '211',
                                             'can_ship_partially': None,
                                             'can_ship_partially_item': None,
                                             'coupon_code': None,
                                             'coupon_rule_name': None,
                                             'created_at': '2014-03-14 16:10:46',
                                             'currency_base_id': None,
                                             'currency_code': None,
                                             'currency_rate': None,
                                             'custbalance_amount': None,
                                             'customer_dob': None,
                                             'customer_email': 'john.doe@example.com',
                                             'customer_firstname': 'John',
                                             'customer_gender': None,
                                             'customer_group_id': '1',
                                             'customer_id': '1',
                                             'customer_is_guest': '0',
                                             'customer_lastname': 'Doe',
                                             'customer_middlename': None,
                                             'customer_note': "salut c'est ma commande",
                                             'customer_note_notify': '0',
                                             'customer_prefix': None,
                                             'customer_suffix': None,
                                             'customer_taxvat': None,
                                             'discount_amount': '0.0000',
                                             'discount_canceled': None,
                                             'discount_description': None,
                                             'discount_invoiced': None,
                                             'discount_refunded': None,
                                             'edit_increment': None,
                                             'email_sent': '1',
                                             'ext_customer_id': None,
                                             'ext_order_id': None,
                                             'forced_do_shipment_with_invoice': None,
                                             'forced_shipment_with_invoice': None,
                                             'gift_message_id': None,
                                             'global_currency_code': 'EUR',
                                             'grand_total': '755.0000',
                                             'hidden_tax_amount': '0.0000',
                                             'hidden_tax_invoiced': None,
                                             'hidden_tax_refunded': None,
                                             'hold_before_state': None,
                                             'hold_before_status': None,
                                             'imported': '0',
                                             'increment_id': '100000006',
                                             'is_hold': None,
                                             'is_multi_payment': None,
                                             'is_virtual': '0',
                                             'items': [{'additional_data': None,
                                                        'amount_refunded': '0.0000',
                                                        'applied_rule_ids': None,
                                                        'base_amount_refunded': '0.0000',
                                                        'base_cost': None,
                                                        'base_discount_amount': '0.0000',
                                                        'base_discount_invoiced': '0.0000',
                                                        'base_discount_refunded': None,
                                                        'base_hidden_tax_amount': None,
                                                        'base_hidden_tax_invoiced': None,
                                                        'base_hidden_tax_refunded': None,
                                                        'base_original_price': '750.0000',
                                                        'base_price': '750.0000',
                                                        'base_price_incl_tax': '750.0000',
                                                        'base_row_invoiced': '0.0000',
                                                        'base_row_total': '750.0000',
                                                        'base_row_total_incl_tax': '750.0000',
                                                        'base_tax_amount': '0.0000',
                                                        'base_tax_before_discount': None,
                                                        'base_tax_invoiced': '0.0000',
                                                        'base_tax_refunded': None,
                                                        'base_weee_tax_applied_amount': '0.0000',
                                                        'base_weee_tax_applied_row_amnt': '0.0000',
                                                        'base_weee_tax_applied_row_amount': '0.0000',
                                                        'base_weee_tax_disposition': '0.0000',
                                                        'base_weee_tax_row_disposition': '0.0000',
                                                        'created_at': '2014-03-14 16:10:46',
                                                        'description': None,
                                                        'discount_amount': '0.0000',
                                                        'discount_invoiced': '0.0000',
                                                        'discount_percent': '0.0000',
                                                        'discount_refunded': None,
                                                        'ext_order_item_id': None,
                                                        'free_shipping': '0',
                                                        'gift_message_available': None,
                                                        'gift_message_id': None,
                                                        'hidden_tax_amount': None,
                                                        'hidden_tax_canceled': None,
                                                        'hidden_tax_invoiced': None,
                                                        'hidden_tax_refunded': None,
                                                        'is_nominal': '0',
                                                        'is_qty_decimal': '0',
                                                        'is_virtual': '0',
                                                        'item_id': '162',
                                                        'locked_do_invoice': None,
                                                        'locked_do_ship': None,
                                                        'name': 'HTC Touch Diamond',
                                                        'no_discount': '0',
                                                        'order_id': '106',
                                                        'original_price': '750.0000',
                                                        'parent_item_id': None,
                                                        'price': '750.0000',
                                                        'price_incl_tax': '750.0000',
                                                        'product_id': '166',
                                                        'product_options': 'a:1:{s:15:"info_buyRequest";a:2:{s:3:"qty";i:1;s:7:"options";a:0:{}}}',
                                                        'product_type': 'simple',
                                                        'qty_backordered': None,
                                                        'qty_canceled': '0.0000',
                                                        'qty_invoiced': '0.0000',
                                                        'qty_ordered': '1.0000',
                                                        'qty_refunded': '0.0000',
                                                        'qty_shipped': '0.0000',
                                                        'quote_item_id': '166',
                                                        'row_invoiced': '0.0000',
                                                        'row_total': '750.0000',
                                                        'row_total_incl_tax': '750.0000',
                                                        'row_weight': '0.3000',
                                                        'sku': 'HTC Touch Diamond',
                                                        'store_id': '1',
                                                        'tax_amount': '0.0000',
                                                        'tax_before_discount': None,
                                                        'tax_canceled': None,
                                                        'tax_invoiced': '0.0000',
                                                        'tax_percent': '0.0000',
                                                        'tax_refunded': None,
                                                        'updated_at': '2014-03-14 16:10:46',
                                                        'weee_tax_applied': 'a:0:{}',
                                                        'weee_tax_applied_amount': '0.0000',
                                                        'weee_tax_applied_row_amount': '0.0000',
                                                        'weee_tax_disposition': '0.0000',
                                                        'weee_tax_row_disposition': '0.0000',
                                                        'weight': '0.3000'}],
                                             'order_currency_code': 'EUR',
                                             'order_id': '106',
                                             'original_increment_id': None,
                                             'payment': {'account_status': None,
                                                         'additional_data': None,
                                                         'additional_information': [],
                                                         'address_status': None,
                                                         'amount': None,
                                                         'amount_authorized': None,
                                                         'amount_canceled': None,
                                                         'amount_ordered': '755.0000',
                                                         'amount_paid': None,
                                                         'amount_refunded': None,
                                                         'anet_trans_method': None,
                                                         'base_amount_authorized': None,
                                                         'base_amount_canceled': None,
                                                         'base_amount_ordered': '755.0000',
                                                         'base_amount_paid': None,
                                                         'base_amount_paid_online': None,
                                                         'base_amount_refunded': None,
                                                         'base_amount_refunded_online': None,
                                                         'base_shipping_amount': '5.0000',
                                                         'base_shipping_captured': None,
                                                         'base_shipping_refunded': None,
                                                         'cc_approval': None,
                                                         'cc_avs_status': None,
                                                         'cc_cid_status': None,
                                                         'cc_debug_request_body': None,
                                                         'cc_debug_response_body': None,
                                                         'cc_debug_response_serialized': None,
                                                         'cc_exp_month': '0',
                                                         'cc_exp_year': '0',
                                                         'cc_last4': None,
                                                         'cc_number_enc': None,
                                                         'cc_owner': None,
                                                         'cc_raw_request': None,
                                                         'cc_raw_response': None,
                                                         'cc_secure_verify': None,
                                                         'cc_ss_issue': None,
                                                         'cc_ss_start_month': '0',
                                                         'cc_ss_start_year': '0',
                                                         'cc_status': None,
                                                         'cc_status_description': None,
                                                         'cc_trans_id': None,
                                                         'cc_type': None,
                                                         'customer_payment_id': None,
                                                         'cybersource_token': None,
                                                         'echeck_account_name': None,
                                                         'echeck_account_type': None,
                                                         'echeck_bank_name': None,
                                                         'echeck_routing_number': None,
                                                         'echeck_type': None,
                                                         'flo2cash_account_id': None,
                                                         'ideal_issuer_id': None,
                                                         'ideal_issuer_title': None,
                                                         'ideal_transaction_checked': None,
                                                         'last_trans_id': None,
                                                         'method': 'checkmo',
                                                         'parent_id': '106',
                                                         'paybox_question_number': None,
                                                         'paybox_request_number': None,
                                                         'payment_id': '106',
                                                         'po_number': None,
                                                         'protection_eligibility': None,
                                                         'quote_payment_id': None,
                                                         'shipping_amount': '5.0000',
                                                         'shipping_captured': None,
                                                         'shipping_refunded': None},
                                             'payment_auth_expiration': None,
                                             'payment_authorization_amount': None,
                                             'payment_authorization_expiration': None,
                                             'paypal_ipn_customer_notified': None,
                                             'protect_code': '4c0584',
                                             'quote_address_id': None,
                                             'quote_id': '114',
                                             'real_order_id': None,
                                             'relation_child_id': None,
                                             'relation_child_real_id': None,
                                             'relation_parent_id': None,
                                             'relation_parent_real_id': None,
                                             'remote_ip': None,
                                             'shipping_address': {'address_id': '212',
                                                                  'address_type': 'shipping',
                                                                  'city': 'Vi',
                                                                  'company': None,
                                                                  'country_id': 'FR',
                                                                  'customer_address_id': '5',
                                                                  'customer_id': '1',
                                                                  'email': None,
                                                                  'fax': None,
                                                                  'firstname': 'john',
                                                                  'gift_message_id': None,
                                                                  'lastname': 'doe',
                                                                  'middlename': None,
                                                                  'parent_id': '106',
                                                                  'postcode': '69100',
                                                                  'prefix': None,
                                                                  'quote_address_id': None,
                                                                  'region': u'Ari\xe8ge',
                                                                  'region_id': '190',
                                                                  'street': '5',
                                                                  'suffix': None,
                                                                  'tax_id': None,
                                                                  'telephone': '25',
                                                                  'vat_id': None,
                                                                  'vat_is_valid': None,
                                                                  'vat_request_date': None,
                                                                  'vat_request_id': None,
                                                                  'vat_request_success': None},
                                             'shipping_address_id': '212',
                                             'shipping_amount': '5.0000',
                                             'shipping_canceled': None,
                                             'shipping_description': 'Flat Rate - Fixed',
                                             'shipping_discount_amount': '0.0000',
                                             'shipping_hidden_tax_amount': '0.0000',
                                             'shipping_incl_tax': '5.0000',
                                             'shipping_invoiced': None,
                                             'shipping_method': 'flatrate_flatrate',
                                             'shipping_refunded': None,
                                             'shipping_tax_amount': '0.0000',
                                             'shipping_tax_refunded': None,
                                             'state': 'new',
                                             'status': 'pending',
                                             'status_history': [{'comment': "salut c'est ma commande",
                                                                 'created_at': '2014-03-14 16:10:46',
                                                                 'entity_name': 'order',
                                                                 'is_customer_notified': '0',
                                                                 'is_visible_on_front': '0',
                                                                 'parent_id': '106',
                                                                 'status': 'pending',
                                                                 'store_id': '1'}],
                                             'store_currency_code': 'EUR',
                                             'store_id': '1',
                                             'store_name': 'Main Website\nMain Store\nEnglish',
                                             'store_to_base_rate': '1.0000',
                                             'store_to_order_rate': '1.0000',
                                             'subtotal': '750.0000',
                                             'subtotal_canceled': None,
                                             'subtotal_incl_tax': '750.0000',
                                             'subtotal_invoiced': None,
                                             'subtotal_refunded': None,
                                             'tax_amount': '0.0000',
                                             'tax_canceled': None,
                                             'tax_invoiced': None,
                                             'tax_percent': None,
                                             'tax_refunded': None,
                                             'total_canceled': None,
                                             'total_due': None,
                                             'total_invoiced': None,
                                             'total_item_count': '1',
                                             'total_offline_refunded': None,
                                             'total_online_refunded': None,
                                             'total_paid': None,
                                             'total_qty_ordered': '1.0000',
                                             'total_refunded': None,
                                             'tracking_numbers': None,
                                             'updated_at': '2014-03-14 16:10:46',
                                             'website_id': u'1',
                                             'weight': '0.3000',
                                             'x_forwarded_for': None},
 ('sales_order.search', (frozenset([('filters', frozenset([('created_at', frozenset([('gt', '2014/03/14 16:00:46')])), ('store_id', frozenset([('in', (u'1',))])), ('state', frozenset([('neq', 'canceled')]))])), ('imported', False)]),)): ['100000006']}
