from . import test_magento2_concurrent_sync
from . import test_magento2_export_invoice
from . import test_magento2_export_picking
from . import test_magento2_export_product_stock
from . import test_magento2_import_metadata
from . import test_magento2_import_partner
from . import test_magento2_import_partner_category
from . import test_magento2_import_product
from . import test_magento2_import_product_category
from . import test_magento2_import_product_image
from . import test_magento2_related_action
from . import test_magento2_sale_order
